(function(g){var window=this;var jta=function(a,b){g.V(a).experiments.g("web_player_gel_logging_killswitch")||a.app.X.V("onLogToGel",{payload_name:"thumbnailLoaded",payload:b})},kta=function(a,b,c,d){var e=b.Vb();
g.P(a.element,"ytp-suggestion-set",!!e.videoId);var f=b.getPlaylistId();d=b.tc(c,d?d:"mqdefault.jpg");var k=b instanceof g.dt?g.ov(b.lengthSeconds):null,l=!!f,f=l&&"RD"==g.Et(f).type,m=b instanceof g.dt?b.Da:null;c={title:b.title,author:b.author,author_and_views:e.shortViewCount?b.author+" \u2022 "+e.shortViewCount:b.author,watch:g.Q("YTP_WATCH_VIDEO_OR_PLAYLIST",{TITLE:b.title},b.title),duration:k,url:b.Yl(c),is_live:m,is_list:l,is_mix:f,background:d?"background-image: url("+d+")":""};b instanceof
g.Ht&&(c.playlist_length=b.getLength());a.update(c)},P8=function(a){var b=g.V(a),c=b.experiments.g("video_wall_moving_thumbnails_hover"),c=b.experiments.g("video_wall_moving_thumbnails_autoplay")||c,d=g.Di||g.tc?{style:"will-change: opacity"}:void 0,e=["ytp-videowall-still"];
b.experiments.g("video_wall_show_text")&&e.push("ytp-show-text");var f={K:"img",$:"ytp-videowall-moving-thumbnail",Z:{src:"{{moving_thumbnail}}"}},b=b.C&&!b.P;g.W.call(this,{K:"a",fa:e,Z:{href:"{{url}}",target:b?"_blank":"","aria-label":"{{watch}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},U:[{K:"div",$:"ytp-videowall-still-image",Z:{style:"{{background}}"}},c?f:null,{K:"span",$:"ytp-videowall-still-info",U:[{K:"span",$:"ytp-videowall-still-info-bg",U:[{K:"span",
$:"ytp-videowall-still-info-content",Z:d,U:[{K:"span",$:"ytp-videowall-still-info-title",U:["{{title}}"]},{K:"span",$:"ytp-videowall-still-info-author",U:["{{author_and_views}}"]},{K:"span",$:"ytp-videowall-still-info-live",U:[g.Q("YTP_LIVE")]},{K:"span",$:"ytp-videowall-still-info-duration",U:["{{duration}}"]}]}]}]},{K:"span",fa:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],U:[{K:"span",$:"ytp-videowall-still-listlabel-icon"},g.Q("YTP_PLAYLIST"),{K:"span",$:"ytp-videowall-still-listlabel-length",
U:[" (",{K:"span",U:["{{playlist_length}}"]},")"]}]},{K:"span",fa:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],U:[{K:"span",$:"ytp-videowall-still-listlabel-mix-icon"},g.Q("YTP_MIX"),{K:"span",$:"ytp-videowall-still-listlabel-length",U:[" (50+)"]}]}]});this.D=b;this.o=a;this.A=null;this.C=0;this.T("click",this.xH);this.T("keypress",this.yH);c&&this.W(this.sa["ytp-videowall-moving-thumbnail"],"load",this.AH);g.V(a).experiments.g("player_interaction_logging")&&(a=a.app.ca,g.gb(a.A,
this),b=String(a.G++),this.element.setAttribute("data-visual-id",b),g.Db(this,(0,g.z)(a.F,a,this)))},lta=function(a){if(5E5<g.Nr(g.V(a.o).F)){var b=a.A.Tl();
b&&(a.C=(0,g.Ol)(),a.update({moving_thumbnail:b}))}},Q8=function(a){g.zv.call(this,a,{K:"div",
fa:["ytp-thumbnail-overlay","ytp-channel-overlay"],U:[{K:"div",$:"ytp-thumbnail-overlay-image",Z:{style:"{{background}}"}},{K:"div",$:"ytp-thumbnail-overlay-curtain"}]})},R8=function(a){var b=g.V(a).experiments.g("moving_thumbnails_autonav"),c={K:"img",
$:"ytp-upnext-moving-thumbnail",Z:{src:"{{moving_thumbnail}}"}},c={K:"div",$:"ytp-upnext",Z:{"aria-label":"{{watch}}"},U:[{K:"div",$:"ytp-thumbnail-overlay-image",Z:{style:"{{background}}"}},b?c:null,{K:"div",$:"ytp-thumbnail-overlay-curtain"},{K:"span",$:"ytp-upnext-top",U:[{K:"span",$:"ytp-upnext-header",U:[g.Q("YTP_PLAYLIST_UP_NEXT")]},{K:"span",$:"ytp-upnext-title",U:["{{title}}"]},{K:"span",$:"ytp-upnext-author",U:["{{author}}"]}]},{K:"a",$:"ytp-upnext-autoplay-icon",Z:{href:"{{url}}"},U:[{K:"svg",
Z:{height:"100%",version:"1.1",viewBox:"0 0 98 98",width:"100%"},U:[{K:"circle",$:"ytp-svg-autoplay-circle",Z:{cx:"49",cy:"49",fill:"#000","fill-opacity":"0.8",r:"48"}},{K:"circle",$:"ytp-svg-autoplay-ring",Z:{cx:"-49",cy:"49","fill-opacity":"0",r:"46.5",stroke:"#FFFFFF","stroke-dasharray":"293","stroke-dashoffset":"-293","stroke-width":"4",transform:"rotate(-90)"}},{K:"polygon",$:"ytp-svg-autoplay-triangle",Z:{fill:"#fff",points:"32,27 72,49 32,71"}}]}]},{K:"span",$:"ytp-upnext-bottom",U:[{K:"span",
$:"ytp-upnext-cancel"},{K:"span",$:"ytp-upnext-paused",U:[g.Q("YTP_AUTOPLAY_PAUSED_2")]}]},{K:"span",$:"ytp-upnext-close"}]};g.W.call(this,c);this.D=null;var d=this.sa["ytp-upnext-cancel"],c=this.sa["ytp-upnext-close"];this.D=new g.W({K:"button",fa:["ytp-upnext-cancel-button","ytp-button"],Z:{tabindex:0,"aria-label":g.Q("YTP_AUTOPLAY_CANCEL")},U:[g.Q("YTP_CANCEL")]});g.L(this,this.D);this.D.T("click",this.Xw,this);this.D.Ja(d);d=new g.W({K:"button",fa:["ytp-upnext-close-button","ytp-button"]});g.L(this,
d);d.T("click",this.Xw,this);d.Ja(c);this.o=a;this.L=this.sa["ytp-svg-autoplay-ring"];this.F=this.C=this.A=this.B=null;this.G=new g.Md(this.Cl,5E3,this);g.L(this,this.G);this.H=0;this.W(this.sa["ytp-upnext-autoplay-icon"],"click",this.uK);this.Uw();this.W(a,"autonavvisibility",this.Uw);this.W(a,"mdxnowautoplaying",this.MJ);this.W(a,"mdxautoplaycanceled",this.NJ);this.W(a,"mdxautoplayupnext",this.lz);3==this.o.Wa()&&(a=(a=g.mm(g.gm(this.o)))?a.ZE():null)&&this.lz(a);b&&(this.J=0,this.W(this.sa["ytp-upnext-moving-thumbnail"],
"load",this.kR))},mta=function(a,b){a.B=b;
kta(a,b,g.V(a.o),"hqdefault.jpg");g.nh(a.element,"ytp-moving-thumbnail-loaded");a.update({moving_thumbnail:"data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"});if(5E5<g.Nr(g.V(a.o).F)){var c=a.B.Tl();c&&(a.J=(0,g.Ol)(),a.update({moving_thumbnail:c}))}},S8=function(a,b){a.A||(g.Pi("a11y-announce",g.Q("YTP_PLAYLIST_UP_NEXT")+" "+a.B.title),a.H=(0,g.Ol)(),a.A=new g.Md((0,g.z)(a.xo,a,b),25),a.xo(b));
g.nh(a.element,"ytp-upnext-autoplay-paused")},U8=function(a){T8(a);
a.H=(0,g.Ol)();a.xo();g.O(a.element,"ytp-upnext-autoplay-paused")},T8=function(a){a.A&&(a.A.dispose(),a.A=null)},V8=function(a,b){g.nv.call(this,{K:"div",
fa:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.o=a;this.X=!1},nta=function(a){a=g.V(a);
return a.kc&&!a.Ga},W8=function(a,b){V8.call(this,a,"videowall-endscreen");
this.da=a;this.ca=b;this.G=0;this.A=[];this.H=this.D=this.C=null;this.J=this.ba=!1;this.F=new g.bo(this);g.L(this,this.F);this.N=new g.Md(g.A(g.O,this.element,"ytp-show-tiles"),0);g.L(this,this.N);var c=new g.W({K:"button",fa:["ytp-button","ytp-endscreen-previous"],Z:{"aria-label":g.Q("YTP_PREVIOUS")},U:[g.Gg()]});g.L(this,c);c.Ja(this.element);c.T("click",this.CP,this);this.P=new g.pu({K:"div",$:"ytp-endscreen-content"});g.L(this,this.P);this.P.Ja(this.element);c=new g.W({K:"button",fa:["ytp-button",
"ytp-endscreen-next"],Z:{"aria-label":g.Q("YTP_NEXT")},U:[g.Hg()]});g.L(this,c);c.Ja(this.element);c.T("click",this.BP,this);this.B=new R8(a);g.L(this,this.B);g.Hm(this.o,this.B.element,5);this.ma()},ota=function(a){return(0,g.R)(a.cg,function(a){return g.qv(a)})},pta=function(a,b,c){return 0==b&&a.C.length&&(b=c/W8.g,2<=c/W8.g&&2<=b&&g.V(a.o).experiments.g("video_wall_emphasize_first"))?2*W8.g:W8.g},X8=function(a){var b=a.ca.Xr();
b!=a.ba&&(a.ba=b,a.o.V("autonavvisibility"))},Y8=function(a){V8.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.A=new Q8(a);g.L(this,this.A);g.Hm(this.o,this.A.element,5);this.B=new g.W(["div","ytp-subscribe-card",["img","ytp-author-image",{src:b.profilePicture}],["div","ytp-subscribe-card-right",["div","ytp-author-name",b.author],["div","html5-subscribe-button-container"]]]);g.L(this,this.B);this.B.Ja(this.element);this.C=new g.yu(g.Q("YTP_SUBSCRIBE"),g.Q("YTP_UNSUBSCRIBE"),!0,b.nz,b.subscribed,"trailer-endscreen",null,a);g.L(this,this.C);this.C.Ja(this.B.sa["html5-subscribe-button-container"]);
this.ma()},Z8=function(a){g.nu.call(this,a);
g.Hh({});this.o=null;this.isAvailable=!0;this.A=new g.bo(this);g.L(this,this.A);this.B=g.V(a);nta(a)?this.o=new W8(this.g,this):this.B.Ga?this.o=new Y8(this.g):this.o=new V8(this.g);g.L(this,this.o);g.Hm(this.g,this.o.element,5);this.ly();this.A.W(a,"videodatachange",this.ly,this);this.A.W(a,"crn_endscreen",this.gP,this);this.A.W(a,"crx_endscreen",this.hP,this)};
g.ca(P8,g.W);g.h=P8.prototype;g.h.Mi=function(){var a=this.A.Vb().videoId,b=this.A.getPlaylistId();g.F2(this.o.app,a,this.A.pd,b,void 0,void 0)};
g.h.xH=function(a){g.Lm(this.o,this);g.tv(a,this.o,!this.o.isFullscreen()&&this.D,this.A.pd||void 0)&&this.Mi()};
g.h.zH=function(){this.Ba(this.B);this.B=null;lta(this)};
g.h.yH=function(a){switch(a.keyCode){case 13:case 32:g.Tk(a)||(this.Mi(),g.Sk(a))}};
g.h.AH=function(a){120<g.Ok(a).naturalWidth&&(g.O(this.element,"ytp-videowall-moving-thumbnail-loaded"),this.A.videoId&&jta(this.o,{isMovingThumbnail:!0,durationLoadingMs:Math.round((0,g.Ol)()-this.C),videoId:this.A.videoId}))};
g.C(Q8,g.zv);Q8.prototype.Fb=function(a){a?this.B.show():g.yv(this.B)};
g.C(R8,g.W);g.h=R8.prototype;g.h.Cl=function(){this.C&&(this.G.stop(),this.Ba(this.F),this.F=null,this.C.close(),this.C=null)};
g.h.Uw=function(){this.Fb(g.hm(this.o))};
g.h.kK=function(){window.focus();this.Cl()};
g.h.xo=function(a){a=a||g.V(this.o).experiments.o("autoplay_time")||1E4;var b=Math.min((0,g.Ol)()-this.H,a);a=Math.min(b/a,1);this.L.setAttribute("stroke-dashoffset",-293*(a+1));1<=a&&3!=this.o.Wa()?this.select(!0):this.A&&this.A.start()};
g.h.select=function(a){var b=g.V(this.o);if(b.experiments.g("autonav_notifications")&&a&&window.Notification&&window.document.hasFocus){var c=window.Notification.permission;g.wm(this.o,"xwebnotifications",{permission:c});"default"==c?window.Notification.requestPermission():"granted"!=c||window.document.hasFocus()||(c=this.B.Vb(),this.Cl(),this.C=new window.Notification(g.Q("YTP_PLAYLIST_UP_NEXT"),{body:c.title,icon:c.tc(b)}),this.F=this.W(this.C,"click",this.kK),this.G.start())}T8(this);this.o.dj(!1,
a)};
g.h.uK=function(a){!g.ef(this.D.element,g.Ok(a))&&g.tv(a,this.o)&&this.select()};
g.h.Xw=function(){g.xm(this.o,"autonavcancel");g.km(this.o,!0)};
g.h.kR=function(a){120<g.Ok(a).naturalWidth&&(g.O(this.element,"ytp-moving-thumbnail-loaded"),jta(this.o,{isMovingThumbnail:!0,durationLoadingMs:Math.round((0,g.Ol)()-this.J),videoId:this.B.Vb().videoId}))};
g.h.MJ=function(a){this.o.Wa();this.show();S8(this,a)};
g.h.lz=function(a){this.o.Wa();this.B&&this.B.Vb().videoId==a.Vb().videoId||mta(this,a)};
g.h.NJ=function(){this.o.Wa();T8(this);this.ma()};
g.h.R=function(){T8(this);this.Cl();R8.M.R.call(this)};
g.C(V8,g.nv);V8.prototype.create=function(){this.X=!0};
V8.prototype.destroy=function(){this.X=!1};
V8.prototype.Co=function(){return!1};
g.C(W8,V8);W8.g=2;g.h=W8.prototype;g.h.create=function(){W8.M.create.call(this);var a=this.o.getVideoData();a&&(this.C=ota(a),this.D=a);this.Xg();this.F.W(this.o,"appresize",this.Xg);this.F.W(this.o,"videodatachange",this.DP);this.F.W(this.o,"autonavchange",this.sA);this.F.W(this.o,"autonavcancel",this.AP);this.F.W(this.element,"transitionend",this.wL)};
g.h.destroy=function(){g.eo(this.F);g.Fb(this.A);this.A=[];this.C=null;W8.M.destroy.call(this);g.nh(this.element,"ytp-show-tiles");this.N.stop()};
g.h.Co=function(){return 1!=this.D.autonavState};
g.h.gk=function(){return g.Im(this.o)&&this.Co()&&!this.H};
g.h.show=function(){W8.M.show.call(this);g.nh(this.element,"ytp-show-tiles");g.V(this.o).isMobile?g.Nd(this.N):this.N.start();(this.J||this.H&&this.H!=this.D.clientPlaybackNonce)&&g.km(this.o,!1);var a=this.gk();g.Im(this.o)&&g.V(this.o).experiments.g("ui_logging")&&this.ca.log({cancelButtonShow:a?"1":"0",state:this.Co()?"enabled":"disabled"});a?(X8(this),2==this.D.autonavState?g.V(this.o).experiments.g("fast_autonav_in_background")&&3==this.o.Xz()?this.B.select(!0):S8(this.B):3==this.D.autonavState&&
U8(this.B)):(g.km(this.o,!0),X8(this))};
g.h.ma=function(){W8.M.ma.call(this);U8(this.B);X8(this)};
g.h.wL=function(a){g.Ok(a)==this.element&&this.Xg()};
g.h.Xg=function(){if(this.C&&this.C.length){var a=g.V(this.o).experiments.g("video_wall_moving_thumbnails_hover");g.O(this.element,"ytp-endscreen-paginate");var b=g.tk(this.element),c=b.width/b.height,d=96/54,e=W8.g,f=W8.g,k=Math.max(b.width/96,2),l=Math.max(b.height/54,2),m=this.C.length,n=Math.pow(W8.g,2),q,t=pta(this,0,l),v=pta(this,1,l);q=m*n+(Math.pow(t,2)-n);q+=Math.pow(v,2)-n;for(q-=n;0<q&&(e<k||f<l);){var x=e/W8.g,B=f/W8.g,E=e<=k-W8.g&&q>=B*n,K=f<=l-W8.g&&q>=x*n;if((x+1)/B*d/c>c/(x/(B+1)*
d)&&K)q-=x*n,f+=W8.g;else if(E)q-=B*n,e+=W8.g;else if(K)q-=x*n,f+=W8.g;else break}d=!1;k=W8.g+t;q>=3*n&&6>=m*n-q&&(f>=k||e>=k)&&v<=W8.g&&(d=!0);q=96*e;n=54*f;c=q/n<c?b.height/n:b.width/q;c=Math.min(c,2);q*=c;n*=c;q*=g.pe(b.width/q||1,1,1.21);n*=g.pe(b.height/n||1,1,1.21);q=Math.floor(Math.min(b.width,q));n=Math.floor(Math.min(b.height,n));b=this.P.element;g.sk(b,q,n);g.Zj(b,{marginLeft:q/-2+"px",marginTop:n/-2+"px"});mta(this.B,this.C[0]);g.P(this.element,"ytp-endscreen-takeover",this.gk());X8(this);
c=q+4;q=n+4;n=0;k=!this.gk();l=!1;for(x=0;x<e;x++)for(B=0;B<f;B++){var K=v>W8.g&&1<=n&&!l?n+1:n,I=0;d&&x>=e-W8.g&&B>=f-W8.g?I=1:0==B%W8.g&&0==x%W8.g&&(B<t&&x<t?0==B&&0==x&&(I=t):v>W8.g&&B>=f-v&&x>=e-v?B==f-v&&x==e-v&&(l=!0,K=1,I=v):I=W8.g);K=g.qe(K+this.G,m);if(0!=I){E=this.A[n];E||(E=new P8(this.o),this.A[n]=E,b.appendChild(E.element));var Qa=Math.floor(q*B/f),Qb=Math.floor(c*x/e),ma=Math.floor(q*(B+I)/f)-Qa-4,Ke=Math.floor(c*(x+I)/e)-Qb-4;g.hk(E.element,Qb,Qa);g.sk(E.element,Ke,ma);g.Zj(E.element,
"transitionDelay",(B+x)/20+"s");g.P(E.element,"ytp-videowall-still-mini",1==I);g.P(E.element,"ytp-videowall-still-large",2<I);K=this.C[K];I=k&&!a;E.A=K;Qa=g.V(E.o);kta(E,K,Qa,g.lh(E.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg");g.nh(E.element,"ytp-videowall-moving-thumbnail-loaded");E.update({moving_thumbnail:"data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"});I?(g.O(E.element,"ytp-videowall-active"),lta(E)):Qa.experiments.g("video_wall_moving_thumbnails_hover")&&
!E.B&&(E.B=E.T("mouseover",E.zH));I=K.pd;K=E.o;g.V(K).experiments.g("player_interaction_logging")&&(K=K.app.ca,I=I&&I.itct,E=E.element.getAttribute("data-visual-id"),g.Jm(K,"onLogServerVeCreated",{id:E,tracking_params:I}));n++}}g.P(this.element,"ytp-endscreen-paginate",n<m);for(a=this.A.length-1;a>=n;a--)E=this.A[a],g.Ye(E.element),g.Eb(E);this.A.length=n}};
W8.A=2;W8.o=1.21;g.h=W8.prototype;g.h.DP=function(){var a=this.o.getVideoData();this.D!=a&&(this.G=0,this.C=ota(a),this.D=a,this.Xg())};
g.h.BP=function(){this.G+=this.A.length;this.Xg()};
g.h.CP=function(){this.G-=this.A.length;this.Xg()};
g.h.YG=function(){return!!this.B.A};
g.h.sA=function(a){1==a?(this.J=!1,this.H=this.D.clientPlaybackNonce,T8(this.B),this.g&&this.Xg()):(this.J=!0,this.g&&this.gk()&&(2==a?S8(this.B):3==a&&U8(this.B)))};
g.h.AP=function(a){if(a){for(a=0;a<this.A.length;a++)g.Mm(this.da,this.A[a],!0);this.sA(1)}else this.H=null,this.J=!1;this.Xg()};
g.C(Y8,V8);Y8.prototype.show=function(){Y8.M.show.call(this);this.A.Fb(!0)};
Y8.prototype.ma=function(){Y8.M.ma.call(this);this.A.Fb(!1)};
g.C(Z8,g.nu);g.h=Z8.prototype;g.h.lA=function(){var a=this.g.getVideoData(),b=!nta(this.g)||!(!a.cg||!a.cg.length),a=g.im(a,"ypc_module"),c=g.i_(this.g.app);return(b||!1)&&!a&&!c};
g.h.Xr=function(){return(this.o instanceof W8||!1)&&this.o.g&&this.o.gk()};
g.h.VG=function(){return this.Xr()?this.o.YG():!1};
g.h.R=function(){g.Em(this.g,"endscreen");Z8.M.R.call(this)};
g.h.load=function(){Z8.M.load.call(this);this.o.show();g.V(this.g).Ga&&.01>Math.random()&&this.log({trailerEndscreenShow:1})};
g.h.log=function(a){g.wm(this.g,"end",a)};
g.h.unload=function(){Z8.M.unload.call(this);this.o.ma();this.o.destroy();this.isAvailable=!1};
g.h.gP=function(a){this.lA()&&(this.o.X||this.o.create(),"load"==a.getId()&&this.load())};
g.h.hP=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.ly=function(){g.Em(this.g,"endscreen");var a=Math.max(1E3*(this.g.getVideoData().lengthSeconds-10),0),a=new g.Nm(a,0x8000000000000,{id:"preload",namespace:"endscreen"}),b=new g.Nm(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.Bm(this.g,[a,b])};
window._exportCheck==g.Aa&&g.oa("ytmod.player.endscreen",Z8,void 0);})(_yt_player);
